name: project0-mpw-9
# either manually started, or on a schedule
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *' # At 4:00 UTC everyday
jobs:

  install:
    env:
        OPENLANE_ROOT:  /home/runner/openlane
        PDK_ROOT:       /home/runner/pdk

    # ubuntu
    runs-on: ubuntu-latest
    steps:

    # checkout the repo to get the scripts
    - uses: actions/checkout@v3

    # build the user project and wrapper
    - name: pdk & openlane
      run: |
        cd $HOME
        git clone https://github.com/efabless/caravel_user_project.git
        cd caravel_user_project/
        git checkout b8efc55a816c11c27d0c363014c5213573b325c2
        make setup
        rm -rf mgmt_core_wrapper/signoff # too big
        rm -rf caravel # wrong version
        git clone https://github.com/efabless/caravel-lite caravel
        cd caravel
        git checkout f7a4b5655bf857f157491e55202ac7619dec1831

    - name: user project example GDS
      run: |
        cd $HOME/caravel_user_project
        make user_proj_example

    - name: user project wrapper GDS
      run: |
        cd $HOME/caravel_user_project
        make user_project_wrapper

    - name: simulation
      run: |
        cd $HOME/caravel_user_project
        make verify-io_ports-rtl

    - name: precheck
      run: |
        cd $HOME/caravel_user_project
        # fixup user_defines
        sed -i '53,$ s/INVALID/MGMT_STD_OUTPUT/' verilog/rtl/user_defines.v
        # new precheck docker command wants to run interactive, fails in GH action
        sed -i 's/docker run -it/docker run/' Makefile
        rm README.md
        touch README.md
        make run-precheck
    
#    - name: timing missing dependencies
#      run: |
#        sudo apt install -y iverilog
#        pip3 install pyverilog
      
    # also needs yosys
#    - name: install oss-cad-suite
#      uses: YosysHQ/setup-oss-cad-suite@v1
#      with:
#          osscadsuite-version: '2022-09-03' # pin the version, latest one fails to work with caravel
#    - run: | 
#        yosys --version

    - name: extract parasitics
      run: |
        cd $HOME/caravel_user_project
        make extract-parasitics
        make create-spef-mapping
        make caravel-sta

    # archive the gds and final report for the user project wrapper
    - name: Archive Wrapper GDS
      uses: actions/upload-artifact@v2
      with:
          name: Wrapper GDS
          path: /home/runner/caravel_user_project/gds/user_project_wrapper.gds

    - name: Archive Wrapper Signoff
      uses: actions/upload-artifact@v2
      with:
          name: Wrapper Report
          path: /home/runner/caravel_user_project/openlane/user_project_wrapper/runs/user_project_wrapper/reports/final_summary_report.csv
   
