name: project0-gfmpw1
# either manually started, or on a schedule
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *' # At 4:00 UTC everyday
jobs:

  install:

    # ubuntu
    runs-on: ubuntu-latest
    steps:

    # checkout the repo to get the scripts
    - uses: actions/checkout@v3

    # build the user project and wrapper
    - name: pdk & openlane
      run: |
        git clone https://github.com/efabless/caravel_user_project.git -b gfmpw-1c
        cd caravel_user_project/
        mkdir verilog/dv/cocotb
        make setup

    - name: user project example GDS
      run: |
        cd $HOME/caravel_user_project
        make user_proj_example

    - name: user project wrapper GDS
      run: |
        cd $HOME/caravel_user_project
        make user_project_wrapper

    - name: precheck
      run: |
        cd $HOME/caravel_user_project
        # fixup user_defines
        sed -i '53,$ s/INVALID/MGMT_STD_OUTPUT/' verilog/rtl/user_defines.v
        rm README.md
        touch README.md
        make precheck
        make run-precheck
  
   # - name: simulation
   #  run: |
   #     cd $HOME/caravel_user_project
   #     make verify-io_ports-rtl

    # archive the gds and final report for the user project wrapper
    - name: Archive Wrapper GDS
      uses: actions/upload-artifact@v2
      with:
          name: Wrapper GDS
          path: /home/runner/caravel_user_project/gds/user_project_wrapper.gds

    - name: Archive Wrapper Signoff
      uses: actions/upload-artifact@v2
      with:
          name: Wrapper Report
          path: /home/runner/caravel_user_project/openlane/user_project_wrapper/runs/user_project_wrapper/reports/final_summary_report.csv
